#include QMK_KEYBOARD_H
#include "g/keymap_combo.h"

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#define KC_COPY LCTL(KC_C)
#define KC_PASTE LCTL(KC_V)

// Light LEDs 6 to 9 and 12 to 15 red when caps lock is active. Hard to ignore!
const rgblight_segment_t PROGMEM capslock_lights[] = RGBLIGHT_LAYER_SEGMENTS(
    {9, 1, HSV_RED}       // Light 4 LEDs, starting with LED 6
);
// Light LEDs 9 & 10 in cyan when keyboard layer 1 is active
const rgblight_segment_t PROGMEM layer1_lights[] = RGBLIGHT_LAYER_SEGMENTS(
    {9, 1, HSV_CYAN}
);
// Light LEDs 11 & 12 in purple when keyboard layer 2 is active
const rgblight_segment_t PROGMEM layer2_lights[] = RGBLIGHT_LAYER_SEGMENTS(
    {9, 1, HSV_PURPLE}
);
// Light LEDs 13 & 14 in green when keyboard layer 3 is active
const rgblight_segment_t PROGMEM layer3_lights[] = RGBLIGHT_LAYER_SEGMENTS(
    {0, 10, HSV_WHITE}
);

// Now define the array of layers. Later layers take precedence
const rgblight_segment_t* const PROGMEM my_rgb_layers[] = RGBLIGHT_LAYERS_LIST(
    layer1_lights,    
    layer2_lights,  
    layer3_lights,
    capslock_lights
);

void keyboard_post_init_user(void) {
    // Enable the LED layers
    rgblight_layers = my_rgb_layers;
}

bool led_update_user(led_t led_state) {
    rgblight_set_layer_state(3, led_state.caps_lock);
    return true;
}

layer_state_t default_layer_state_set_user(layer_state_t state) {
    return state;
}

layer_state_t layer_state_set_user(layer_state_t state) {
    rgblight_set_layer_state(0, layer_state_cmp(state, 1));
    rgblight_set_layer_state(1, layer_state_cmp(state, 2));
    rgblight_set_layer_state(2, layer_state_cmp(state, 3));
    return state;
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_60_hhkb(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_LBRC, KC_RBRC, KC_BSLS, KC_GRV, KC_TAB, KC_QUOT, KC_COMM, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, KC_SLSH, KC_EQL, KC_BSPC, KC_LCTL, KC_A, KC_O, KC_E, KC_U, KC_I, KC_D, KC_H, KC_T, KC_N, KC_S, KC_MINUS, KC_ENT, KC_LSFT, KC_SCLN, KC_Q, KC_J, KC_K, KC_X, KC_B, KC_M, KC_W, KC_V, KC_Z, KC_RSFT, MO(1), KC_LALT, KC_LGUI, LT(3, KC_SPC), KC_LALT, KC_PSTE),
    [1] = LAYOUT_60_hhkb(KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_VOLD, KC_VOLU, KC_CAPS, KC_GRV, KC_NO, KC_PGUP, KC_NO, KC_NO, KC_F16, KC_F19, KC_F22, KC_NO, KC_UP, KC_PAUS, KC_MUTE, KC_DEL, KC_TRNS, KC_WREF, KC_HOME, KC_PGDN, KC_END, KC_NO, KC_F17, KC_F20, KC_F23, KC_LEFT, KC_DOWN, KC_RGHT, KC_PENT, KC_TRNS, KC_BSLS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F21, KC_F24, KC_NO, KC_PSCR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(2), KC_TRNS),
	[2] = LAYOUT_60_hhkb(KC_PWR, RGB_M_P, RGB_M_B, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RGB_TOG, RGB_HUI, RGB_SAI, RGB_VAI, RGB_SPI, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RGB_HUD, RGB_SAD, RGB_VAD, RGB_SPD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RESET),
    [3] = LAYOUT_60_hhkb(KC_ESC , KC_F1 , KC_F2 , KC_F3 , KC_F4 , KC_F5 , KC_F6 , KC_F7 , KC_F8 , KC_F9 , KC_F10 , KC_F11 , KC_F12 , KC_NO , KC_NO , KC_TAB , LCTL(KC_X) , KC_NO , KC_LEFT_CURLY_BRACE, KC_RIGHT_CURLY_BRACE , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_DEL , KC_LCTL , KC_COPY , KC_PSTE , KC_LPRN , KC_RPRN , KC_NO , KC_HOME , KC_LEFT , KC_DOWN , KC_UP , KC_RGHT , KC_END , KC_ENT , KC_LSFT , LCTL(KC_S) , KC_NO , KC_LBRC , KC_RBRC , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_RSFT , KC_NO , KC_TRNS , KC_TRNS , KC_TRNS , KC_NO , KC_NO )
};